// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0yuh02RzfONO1LuoOqh_T2IVgQIr2C4',
    appId: '1:476375681005:web:5e32025b03e11f6077c9e4',
    messagingSenderId: '476375681005',
    projectId: 'fooddeliveryapp-876f2',
    authDomain: 'fooddeliveryapp-876f2.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-876f2.appspot.com',
    measurementId: 'G-7S2HQS8XXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbRj1gzwLWYFkRovvUWNwm4v3PDBVTarM',
    appId: '1:476375681005:android:2e881868680535f677c9e4',
    messagingSenderId: '476375681005',
    projectId: 'fooddeliveryapp-876f2',
    storageBucket: 'fooddeliveryapp-876f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwH7Azphk9kbP1Nm5nB-S_pjkrxU2biMU',
    appId: '1:476375681005:ios:76e9af2b779d178877c9e4',
    messagingSenderId: '476375681005',
    projectId: 'fooddeliveryapp-876f2',
    storageBucket: 'fooddeliveryapp-876f2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwH7Azphk9kbP1Nm5nB-S_pjkrxU2biMU',
    appId: '1:476375681005:ios:76e9af2b779d178877c9e4',
    messagingSenderId: '476375681005',
    projectId: 'fooddeliveryapp-876f2',
    storageBucket: 'fooddeliveryapp-876f2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU0yuh02RzfONO1LuoOqh_T2IVgQIr2C4',
    appId: '1:476375681005:web:3908cfcbbcfe5b9a77c9e4',
    messagingSenderId: '476375681005',
    projectId: 'fooddeliveryapp-876f2',
    authDomain: 'fooddeliveryapp-876f2.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-876f2.appspot.com',
    measurementId: 'G-E6JWMM39FF',
  );
}
